require("core.options")
require("core.keymaps")
require("lazy_config")
require("neovide")

-- plugins
require("plugins/colorscheme")
require("plugins/telescope")
require("plugins/lualine")
require("plugins/nvim-tree")
require("plugins/bufferline")
require("plugins/treesitter")
require("plugins/autopairs")
require("plugins/indent-line")
require("plugins/terminal")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/gitsigns")
require("plugins/format")
